
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(Components)/navbar/navbar";
import Home from "./(Components)/home/page";
const inter = Inter({ subsets: ["latin"] });
import '@fortawesome/fontawesome-free/css/all.min.css'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
      
      <body className={inter.className}>
 
      <Navbar/>
      {children}
     
      
    
      

     </body>
      
    </html>
 
  );
}
